---
- hosts: 3.120.108.70
  become: yes
  tasks:
  - name: install mariadb server
    yum:
     name=mariadb-server
     state=latest
    tags:  
    - install
    - all
  - name: start mariadb
    service:
      name=mariadb
      state=started
    tags:
    - start
    - all 
