---
- hosts: linux
  tasks:
  - name: print output
    shell: echo $HOSTNAME " i am in training"
    register: output
  - debug: msg="standard output={{output.stdout}}"
  - debug: msg="standard error={{output.stderr}}"
